language: node_js
node_js:
  - "stable"
script:
  - npm run test:coverage
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:coveralls
cache:
  directories:
    - node_modules
